### ISSUE TITLE
corefonts.py fails with HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by digulla** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE#9]
During launch, I get a ton of errors for core fonts.

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/steam/compatibilitytools.d/Proton-GE/protonfixes/corefonts.py", line 48, in download_file
    with urllib.request.urlopen(url, files) as font:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

Also, later, I get a message from "ProtonFixes" that it will link fonts:

Creating MS Core font links in $HOME/.local/share/Steam/steamapps/compatdata/$GAME_ID/pfx/drive_c/windows/Fonts

which is confusing because of the links end up in $HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/$GAME_ID/pfx/drive_c/windows/Fonts

When I checked the links, they point to /app/share/steam/compatibilitytools.d/Proton-GE/share/fonts/ and in there to OSS true type fonts but the links are all dead:

```
arialbd.ttf -> /app/share/steam/compatibilitytools.d/Proton-GE/share/fonts/LiberationSans-Bold.ttf
arial.ttf -> /app/share/steam/compatibilitytools.d/Proton-GE/share/fonts/LiberationSans-Regular.ttf
cour.ttf -> /app/share/steam/compatibilitytools.d/Proton-GE/share/fonts/LiberationMono-Regular.ttf
msyh.ttf -> /app/share/steam/compatibilitytools.d/Proton-GE/share/fonts/SourceHanSansSCRegular.otf
times.ttf -> /app/share/steam/compatibilitytools.d/Proton-GE/share/fonts/LiberationSerif-Regular.ttf
```

/app doesn't exist. I guess that's also mapped from somewhere?

**Comment by Lctrs** [comment]
Version 6.0-GE-1 is now available. Does it fix your issue ?

**Comment by chewi** [comment]
This is present in 6.0-GE-1. It's simons-public/protonfixes#148. I spotted this myself before realising it was already fixed upstream.

**Comment by digulla** [comment]
Still broken in 6.1. The fix linked in the previous comment works for me why I apply it manually to $HOME/.local/share/flatpak/runtime/com.valvesoftware.Steam.CompatibilityTool.Proton-GE/x86_64/stable/faaea02300735eab85eb3da1532e4271031992b39da51f111dbded563887fe51/files/protonfixes/corefonts.py

**Comment by Lctrs** [comment]
Yeah I know. That's because GloriousEggroll doesn't include https://github.com/simons-public/protonfixes in Proton-GE but its own fork located [here](https://github.com/GloriousEggroll/protonfixes).
I've proposed to backport the patch in https://github.com/GloriousEggroll/protonfixes/pull/12 but GloriousEggroll is not very reactive on the PR. So wait & see.

**Comment by Lctrs** [comment]
Closed by #16.
